const IS_RESPONSE_UPDATE = "IS_RESPONSE_UPDATE";
const TRY_UPDATE = "TRY_UPDATE";
const IS_LOADING_UPDATE = "IS_LOADING_UPDATE";
const IS_ERROR_UPDATE = "IS_ERROR_UPDATE";


export {
    IS_ERROR_UPDATE,
    IS_LOADING_UPDATE,
    IS_RESPONSE_UPDATE,
    TRY_UPDATE
}