const IS_RESPONSE_CREATE = "IS_RESPONSE_CREATE";
const TRY_CREATE = "TRY_CREATE";
const IS_LOADING_CREATE = "IS_LOADING_CREATE";
const IS_ERROR_CREATE = "IS_ERROR_CREATE";


export {
    IS_ERROR_CREATE,
    IS_LOADING_CREATE,
    IS_RESPONSE_CREATE,
    TRY_CREATE
}