const IS_RESPONSE_DELETE = "IS_RESPONSE_DELETE";
const TRY_DELETE = "TRY_DELETE";
const IS_LOADING_DELETE = "IS_LOADING_DELETE";
const IS_ERROR_DELETE = "IS_ERROR_DELETE";


export {
    IS_ERROR_DELETE,
    IS_LOADING_DELETE,
    IS_RESPONSE_DELETE,
    TRY_DELETE
}